services:
  nginx:
    image: nginx:alpine
    container_name: autoserve-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker_configs/nginx:/etc/nginx/conf.d
      - ./docker_configs/nginx-main.conf:/etc/nginx/nginx.conf
    networks:
      - autoserve
    restart: unless-stopped
    labels:
      - "autoserve.service=nginx"
      - "autoserve.managed=true"

  # redis:
  #   image: redis:alpine
  #   container_name: autoserve-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - autoserve_redis_data:/data
  #   networks:
  #     - autoserve
  #   restart: unless-stopped
  #   labels:
  #     - "autoserve.service=redis"
  #     - "autoserve.managed=true"

  controller:
    build:
      context: .
      dockerfile: docker_configs/Dockerfile.controller
    container_name: autoserve-controller
    ports:
      - "${AUTOSERVE_PORT}:${AUTOSERVE_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker_configs/nginx:/nginx-config
      - autoserve_db_data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env.docker
    networks:
      - autoserve
    depends_on:
      - nginx
    restart: unless-stopped
    labels:
      - "autoserve.service=controller"
      - "autoserve.managed=true"

networks:
  autoserve:
    driver: bridge
    name: autoserve

volumes:
  autoserve_db_data:
