site_name: AutoServe Documentation
site_url: https://arjuuuuunnnnn.github.io/AutoServe/
site_description: AutoServe - Container Orchestration and Auto-Scaling Platform
use_directory_urls: true
repo_url: https://github.com/arjuuuuunnnnn/AutoServe
repo_name: arjuuuuunnnnn/AutoServe

nav:
  - Home: README.md
  
  - User Guide:
    - Quick Start: docs/user-guide/quick-start.md
    - CLI Reference: docs/user-guide/cli-reference.md
    - Application Specification: docs/user-guide/app-spec.md
    - Configuration: docs/user-guide/configuration.md
    - API Reference: docs/user-guide/api-reference.md
    - Troubleshooting: docs/user-guide/troubleshooting.md
    
  - Developer Guide:
    - Architecture Overview: docs/developer-guide/architecture.md
    - Core Components: docs/developer-guide/components.md
    - Leader Election: docs/developer-guide/leader-election.md
    - Database Schema: docs/developer-guide/database.md
    - Scaling Algorithm: docs/developer-guide/scaling.md
    - Health Monitoring: docs/developer-guide/health.md
    - Load Balancing: docs/developer-guide/load-balancing.md
    - Development Setup: docs/developer-guide/development.md
    - Extensions: docs/developer-guide/extensions.md
    
  - Examples:
    - Sample Applications: docs/examples/applications.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

site_dir: site

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arjuuuuunnnnn/AutoServe
  version:
    provider: mike

