site_name: AutoServe
site_url: https://arjuuuuunnnnn.github.io/AutoServe/
use_directory_urls: false

nav:
  - Home: README.md

theme:
  name: material
site_dir: site

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true

